INSERT INTO symptoms (slug, name, category, is_builtin, created_by_user_id, is_active) VALUES
  ('headache', 'Headache', 'Physical Pain', TRUE, NULL, TRUE),
  ('joint-pain', 'Joint Pain', 'Physical Pain', TRUE, NULL, TRUE),
  ('back-pain', 'Back Pain', 'Physical Pain', TRUE, NULL, TRUE),
  ('muscle-pain', 'Muscle Pain', 'Physical Pain', TRUE, NULL, TRUE),
  ('neck-pain', 'Neck Pain', 'Physical Pain', TRUE, NULL, TRUE),
  ('stomach-pain', 'Stomach Pain', 'Physical Pain', TRUE, NULL, TRUE),
  ('fatigue', 'Fatigue', 'Physical Other', TRUE, NULL, TRUE),
  ('dizziness', 'Dizziness', 'Physical Other', TRUE, NULL, TRUE),
  ('drowsiness', 'Drowsiness', 'Physical Other', TRUE, NULL, TRUE),
  ('nausea', 'Nausea', 'Physical Other', TRUE, NULL, TRUE),
  ('dry-mouth', 'Dry Mouth', 'Physical Other', TRUE, NULL, TRUE),
  ('heart-palpitations', 'Heart Palpitations', 'Physical Other', TRUE, NULL, TRUE),
  ('blurred-vision', 'Blurred Vision', 'Physical Other', TRUE, NULL, TRUE),
  ('restlessness', 'Restlessness', 'Physical Other', TRUE, NULL, TRUE),
  ('anxiety', 'Anxiety', 'Mental', TRUE, NULL, TRUE),
  ('irritability', 'Irritability', 'Mental', TRUE, NULL, TRUE),
  ('sense-of-dread', 'Sense of Dread', 'Mental', TRUE, NULL, TRUE),
  ('mood-swings', 'Mood Swings', 'Mental', TRUE, NULL, TRUE),
  ('feeling-overwhelmed', 'Feeling Overwhelmed', 'Mental', TRUE, NULL, TRUE),
  ('brain-fog', 'Brain Fog', 'Cognitive', TRUE, NULL, TRUE),
  ('forgetfulness', 'Forgetfulness', 'Cognitive', TRUE, NULL, TRUE),
  ('difficulty-focusing', 'Difficulty Focusing', 'Cognitive', TRUE, NULL, TRUE),
  ('pessimism', 'Pessimism', 'Cognitive', TRUE, NULL, TRUE),
  ('racing-thoughts', 'Racing Thoughts', 'Cognitive', TRUE, NULL, TRUE)
ON DUPLICATE KEY UPDATE name = VALUES(name), category = VALUES(category), is_builtin = TRUE,
  created_by_user_id = NULL, is_active = TRUE;
